CREATE DATABASE SENAI_HROADS_MANHA;

USE SENAI_HROADS_MANHA;

CREATE TABLE CLASSES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_HABILIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE
	,ID_TIPO_HAB INT FOREIGN KEY REFERENCES TIPOS_HABILIDADES(ID)
);

ALTER TABLE HABILIDADES
ALTER COLUMN ID_TIPO_HAB INT NOT NULL;

CREATE TABLE CLASSES_HABILIDADES(
	ID_CLASSE INT NOT NULL FOREIGN KEY REFERENCES CLASSES(ID)
	,ID_HABILIDADES INT NOT NULL FOREIGN KEY REFERENCES HABILIDADES(ID)
);

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE
	,ID_CLASSE INT NOT NULL FOREIGN KEY REFERENCES CLASSES(ID)
	,CAP_MAX_VIDA INT NOT NULL
	,CAP_MAX_MANA INT NOT NULL
	,DATA_ATUAL DATE
	,DATA_CRIACAO DATE NOT NULL 
);
