USE SENAI_HROADS_MANHA;

--SELECIONAR TODOS OS PERSONAGENS (ITEM 6)
SELECT * FROM PERSONAGENS ORDER BY ID ASC;

--SELECIONAR TODAS AS CLASSES (ITEM 7)
SELECT * FROM CLASSES ORDER BY ID ASC;

--SELECIONAR SOMENTE O NOME DAS CLASSES (ITEM 8)
SELECT NOME FROM CLASSES ORDER BY ID ASC;

--SELECIONAR TODAS AS HABILIDADES (ITEM 9)
SELECT * FROM HABILIDADES ORDER BY ID ASC;

--REALIZAR A CONTAGEM DE QUANTAS HABILIDADES ESTÃO CADASTRADAS
--(ITEM 10)
SELECT COUNT(ID) AS QUANT_HAB FROM HABILIDADES;

--SELECIONAR SOMENTE OS IDs DAS HABILIDADES
--CLASSIFICANDO-OS POR ORDEM CRESCENTE (ITEM 11)
SELECT ID FROM HABILIDADES ORDER BY ID ASC;

--SELECIONAR TODOS OS TIPOS DE HABILIDADES (ITEM 12)
SELECT * FROM TIPOS_HABILIDADES;

--SELECIONAR TODAS AS HABILIDADES 
--E A QUAIS TIPOS DE HABILIDADES ELAS FAZEM PARTE (ITEM 13)
SELECT * FROM
	HABILIDADES H INNER JOIN TIPOS_HABILIDADES TH
ON
	H.ID_TIPO_HAB = TH.ID;

--SELECIONAR TODOS OS PERSONAGENS E SUAS RESPECTIVAS CLASSES
--(ITEM 14)
SELECT * FROM
	PERSONAGENS P INNER JOIN CLASSES CS
ON
	P.ID_CLASSE = CS.ID;

--SELECIONAR TODOS OS PERSONAGENS E AS CLASSES
--MESMO SEM CORRESPONDÊNCIA (ITEM 15)
SELECT * FROM
	PERSONAGENS P FULL OUTER JOIN CLASSES CS
ON
	P.ID_CLASSE = CS.ID;

--SELECIONAR TODAS AS CLASSES E SUAS RESPECTIVAS HABILIDADES
--(ITEM 16)
SELECT * FROM
	CLASSES CS FULL OUTER JOIN CLASSES_HABILIDADES CH
ON
	CS.ID = CH.ID_CLASSE
				FULL OUTER JOIN HABILIDADES H
				ON H.ID = CH.ID_HABILIDADE;

--SELECIONAR TODAS AS HABILIDADES E SUAS CLASSES
--SOMENTE AS CORRESPONDENTES
--(ITEM 17)
SELECT * FROM
	HABILIDADES H INNER JOIN CLASSES_HABILIDADES CH
ON
	H.ID = CH.ID_HABILIDADE
				INNER JOIN CLASSES CS
				ON CS.ID = CH.ID_CLASSE;

--SELECIONAR TODAS AS HABILIDADES E SUAS CLASSES
--MESMO SEM CORRESPONDÊNCIA
--(ITEM 18)

SELECT * FROM
	HABILIDADES H FULL OUTER JOIN CLASSES_HABILIDADES CH
ON
	H.ID = CH.ID_HABILIDADE
				FULL OUTER JOIN CLASSES CS
				ON CS.ID = CH.ID_CLASSE;